[package]
name = "ere-pico"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
zkvm-interface = { workspace = true }
thiserror = "2"
anyhow = "*"                          #TOOD: remove for  thiserror

[lints]
workspace = true
