name: Check Base Docker Image

on:
  push:
    branches:
      - master
    paths:
      - 'docker/base/**'
      - '.github/workflows/check_base_image.yml'
  pull_request:
    branches:
      - master
    paths:
      - 'docker/base/**'
      - '.github/workflows/check_base_image.yml'
  workflow_dispatch:

jobs:
  build_base_image:
    name: Build Base Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker base image
        run: |
          docker build \
            --file docker/base/Dockerfile.base \
            --tag ere-base-check:latest \
            .