name: Test SP1 (Docker)

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test-sp1-via-docker-build:
    name: Build SP1 Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build ere-base image
        run: |
          docker build \
            --tag ere-base:latest \
            --file docker/base/Dockerfile.base .

      - name: Build ere-builder-sp1 image
        run: |
          docker build \
            --tag ere-builder-succinct:latest \
            --file docker/sp1/Dockerfile .
